export const login = 'driver/login'
export const register = 'driver/register'
export const verifyOtp = 'driver/verify-token'
export const userSelf = 'self'
export const mailLogin = 'driver/email/login'
